---

- name: Install packages required to install Mesos from source
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ all_apt_cache_valid_time }}"
  become: yes
  with_items:
    - git
    - openjdk-8-jdk
    - autoconf
    - libtool
    - build-essential
    - python-dev
    - libcurl4-nss-dev
    - libsasl2-dev
    - libsasl2-modules
    - maven
    - libapr1-dev
    - libsvn-dev
    - zlib1g-dev

- name: Clone Mesos repository
  git:
    repo: https://git-wip-us.apache.org/repos/asf/mesos.git
    dest: "{{ mesos_build_directory }}"
    version: "{{ mesos_version }}"

- name: Bootstrap for building Mesos
  shell: ./bootstrap
  args:
    chdir: "{{ mesos_build_directory }}"
    creates: "{{ mesos_build_directory }}/aclocal.m4"

- name: Configure Mesos build
  shell: ./configure
  args:
    chdir: "{{ mesos_build_directory }}"
    creates: "{{ mesos_build_directory }}/Makefile"

- name: Build Mesos
  make:
    chdir: "{{ mesos_build_directory }}"

- name: Install Mesos
  make:
    chdir: "{{ mesos_build_directory }}"
    target: install
  become: yes

- name: Cleanup build directory
  file:
    state: absent
    path: "{{ mesos_build_directory }}"