ARG DOCKER_REPOSITORY=postgres
ARG POSTGRES_VERSION=9.5

FROM ${DOCKER_REPOSITORY}:${POSTGRES_VERSION}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         openssh-server \
         python \
         python-pip \
    && rm -rf /var/lib/apt/lists/*

RUN sed -ri "s/^PermitRootLogin\s+.*/PermitRootLogin yes/" /etc/ssh/sshd_config \
    && sed -ri "s/UsePAM yes/#UsePAM yes/g" /etc/ssh/sshd_config
RUN mkdir /var/run/sshd
ARG root_password=root
RUN echo "root:${root_password}" | chpasswd
EXPOSE 22

ADD tests/docker/run-target.sh /run.sh

CMD ["./run.sh"]
