FROM python:3

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        sshpass \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /postgres-s3-backup
ADD tests/runner-requirements.txt tests/runner-requirements.txt
RUN pip --disable-pip-version-check install -r tests/runner-requirements.txt
ADD . .

WORKDIR /postgres-s3-backup/tests
ENV ANSIBLE_HOST_KEY_CHECKING=False
CMD ["ansible-playbook", "-i", "inventory.ini", "-vvv", "test.yml"]
#CMD ["ansible-playbook", "-i", "inventory.ini", "test.yml"]
